version: '3.8'

services:
  postgres:
    image: postgres:15.6
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - backend

  keycloak_web:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: 77.238.232.143
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: cryptad
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
    command: start-dev
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - backend

  patients_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8097"
    environment:
      spring_profiles_active: dev
    networks:
      - backend


networks:
  backend:


volumes:
  postgres_data:

